AWSTemplateFormatVersion: 2010-09-09
Description: Resume challenge stack 

Resources:
  ResumesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: resume
      AttributeDefinitions:
        - AttributeName: interviewee
          AttributeType: N
      KeySchema:
        - AttributeName: interviewee
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
        
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt ResumesTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ResumeLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: resume
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Code:
        S3Bucket: resume-app-challenge
        S3Key: lambda_function.zip
      Timeout: 10
      MemorySize: 128

  ResumeLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResumeLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeApiGateway}/*/GET/resume

  ResumeApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: resume
      ProtocolType: HTTP
      IpAddressType: ipv4

  ResumeApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ResumeApiGateway
      StageName: live
      Description: Live Stage
      AutoDeploy: true

  ResumeIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ResumeApiGateway
      Description: Lambda integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: 2.0
      IntegrationUri: !GetAtt ResumeLambdaFunction.Arn

  ResumeApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ResumeApiGateway
      RouteKey: GET /resume
      Target: !Sub integrations/${ResumeIntegration}